name: habit_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

  

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app-icon.png"
  image_path_android: "assets/images/app-icon.png"
  adaptive_icon_background: "assets/images/app-icon-background.png"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
